// Local config plugin bundling three native Android changes that have no
// first-party Expo plugin coverage. android/ is gitignored (regenerated by
// `expo prebuild`), so anything hand-edited there directly is invisible to
// git and gets silently wiped on a clean prebuild — this plugin is what
// makes these survive that regeneration.
//
// Covers:
//   1. Gradle JVM heap/metaspace — fixes an OutOfMemoryError during
//      release Kotlin/KSP compilation (assembleRelease/bundleRelease).
//   2. Release signing config — points `release` build type at the real
//      release keystore instead of the stock debug keystore (Play Store
//      rejects debug-signed AABs outright). Passwords are read from
//      android/gradle.properties (gitignored, filled in locally — see
//      that file's AYUXA_RELEASE_* keys) so no secret lives in this repo.
//   3. Network Security Config — SSL pinning for the app's own backend
//      (api.ayuxacare.com) only. See network_security_config.xml's own
//      header comment for why it's pinned at the CA/root level rather
//      than the leaf cert, and why there is deliberately NO runtime
//      kill-switch (Android bakes this into the APK at build time).
//   4. R8 minify + resource shrinking for release builds — off by default
//      in the RN/Expo template (both gated behind gradle.properties flags
//      that are never set). Google Play Console's "App optimisation"
//      check flags an unobfuscated release APK/AAB under its Obfuscation
//      category; this is what actually fixes that, not just silences it.
//   5. FLAG_SECURE set in MainActivity.onCreate(), before super.onCreate()
//      runs — closes the native-boot gap that expo-screen-capture's JS-side
//      usePreventScreenCapture() can't: that hook only sets the flag from a
//      React useEffect, which can't fire until JS boots and the root layout
//      mounts, leaving screenshots/recording possible during native launch
//      and the splash screen. Setting it here means the window is marked
//      secure before the Activity finishes creating, with no gap at all.
const fs = require('fs');
const path = require('path');
const { withGradleProperties, withAppBuildGradle, withAndroidManifest, withDangerousMod, withMainActivity } = require('@expo/config-plugins');

const NETWORK_SECURITY_CONFIG_XML = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Network security config for Ayuxa:
  - Enforces strict HTTPS (cleartextTrafficPermitted="false") for api.ayuxacare.com.
  - Validates TLS against Android system trust anchors.
  - Blocks cleartext downgrade attacks while ensuring compatibility across all Android versions, CDNs, and certificate renewals.
-->
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" />
        </trust-anchors>
    </base-config>
    <domain-config cleartextTrafficPermitted="false">
        <domain includeSubdomains="true">api.ayuxacare.com</domain>
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </domain-config>
</network-security-config>
`;

// Debug builds additionally need to reach the local Metro dev server over
// plain http:// on a LAN IP (e.g. 10.x.x.x) — cleartextTrafficPermitted
// alone doesn't scope pinning away from that traffic, it just allows
// cleartext in general (which debug builds already need for Metro
// regardless of pinning). Resource merging prefers this debug-variant file
// over the main one automatically, same as the existing
// android:usesCleartextTraffic override in src/debug/AndroidManifest.xml.
const NETWORK_SECURITY_CONFIG_DEBUG_XML = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Debug-only override: no pinning at all, cleartext allowed everywhere.
  This file is NEVER included in a release build (Android resource
  merging: src/debug/res only applies to the debug variant) — see the
  main network_security_config.xml for the real production config.
-->
<network-security-config>
    <base-config cleartextTrafficPermitted="true" />
</network-security-config>
`;

const setGradleProperty = (modResults, key, value) => {
    const existing = modResults.find((item) => item.type === 'property' && item.key === key);
    if (existing) {
        existing.value = value;
    } else {
        modResults.push({ type: 'property', key, value });
    }
};

const withGradleJvmMemory = (config) => {
    return withGradleProperties(config, (config) => {
        setGradleProperty(config.modResults, 'org.gradle.jvmargs', '-Xmx4096m -XX:MaxMetaspaceSize=1024m');
        return config;
    });
};

// Both flags default to 'false' in the stock template's build.gradle when
// unset (see app/build.gradle's findProperty(...) ?: false), so a release
// build was shipping fully unobfuscated, unshrunk code -- exactly what
// Google Play's "App optimisation" report flags under Obfuscation.
const withReleaseOptimization = (config) => {
    return withGradleProperties(config, (config) => {
        setGradleProperty(config.modResults, 'android.enableMinifyInReleaseBuilds', 'true');
        setGradleProperty(config.modResults, 'android.enableShrinkResourcesInReleaseBuilds', 'true');
        return config;
    });
};

// android/app/proguard-rules.pro is gitignored (regenerated by prebuild),
// same problem as everything else in this file -- hand edits there vanish
// on the next clean prebuild. Most native deps (Reanimated, expo-modules-core,
// Google Sign-In) ship their own consumer ProGuard rules bundled in the AAR,
// which R8 merges in automatically -- no action needed for those. The one
// exception here is react-native-razorpay's underlying com.razorpay:standard-core
// SDK, which does NOT bundle consumer rules and documents its own required
// keep-set (https://razorpay.com/docs/payments/payment-gateway/android-integration/standard/proguard/)
// because its webview JS bridge relies on reflection that R8 would otherwise
// strip or rename, silently breaking payment callbacks in a release build.
const PROGUARD_RULES = `# Add project specific ProGuard rules here.
# Managed by plugins/withAndroidHardening.js -- edit there, not here.

# react-native-reanimated
-keep class com.swmansion.reanimated.** { *; }
-keep class com.facebook.react.turbomodule.** { *; }

# Razorpay checkout SDK (com.razorpay:standard-core) -- required by Razorpay,
# not bundled as a consumer rule by their AAR. Reflection-based JS bridge
# callbacks (PaymentResultListener etc.) would otherwise be stripped/renamed.
-keepclassmembers class * implements com.razorpay.PaymentResultListener {
    public void onPaymentSuccess(java.lang.String);
    public void onPaymentError(int, java.lang.String);
}
-keep class com.razorpay.** { *; }
-optimizations !method/inlining/*
-keepattributes *Annotation*
-dontwarn com.razorpay.**

# Google Play In-App Updates (com.google.android.play:app-update / app-update-ktx)
# via expo-in-app-updates. Unlike Reanimated/expo-modules-core, this AAR does
# NOT bundle its own consumer ProGuard rules -- without this, R8 can rename/strip
# the Play Core API surface the native module calls into, breaking checkForUpdate/
# startUpdate at runtime in a release build without any compile-time error.
-keep class com.google.android.play.core.** { *; }
-dontwarn com.google.android.play.core.**

# Add any project specific keep options here:
`;

const withRazorpayProguardRules = (config) => {
    return withDangerousMod(config, [
        'android',
        async (config) => {
            const file = path.join(config.modRequest.platformProjectRoot, 'app/proguard-rules.pro');
            fs.writeFileSync(file, PROGUARD_RULES);
            return config;
        },
    ]);
};

// android/gradle.properties is fully regenerated on every `expo prebuild`,
// so storing the release keystore passwords there directly means they get
// silently wiped on every clean prebuild. Reading them from env vars here
// (same pattern as EXPO_PUBLIC_GOOGLE_MAPS_API_KEY elsewhere in this repo)
// means one entry in .env / an EAS secret survives every regeneration
// automatically -- nothing to remember to re-type.
const withReleaseSigningProperties = (config) => {
    return withGradleProperties(config, (config) => {
        setGradleProperty(config.modResults, 'AYUXA_RELEASE_STORE_FILE', 'ayuxa-release.keystore');
        setGradleProperty(config.modResults, 'AYUXA_RELEASE_KEY_ALIAS', 'ayuxa-release');
        setGradleProperty(config.modResults, 'AYUXA_RELEASE_STORE_PASSWORD', process.env.RELEASE_KEYSTORE_PASSWORD || '');
        setGradleProperty(config.modResults, 'AYUXA_RELEASE_KEY_PASSWORD', process.env.RELEASE_KEY_PASSWORD || '');
        return config;
    });
};

const withReleaseSigningConfig = (config) => {
    return withAppBuildGradle(config, (config) => {
        const contents = config.modResults.contents;
        if (contents.includes('AYUXA_RELEASE_STORE_PASSWORD')) return config; // already applied

        const signingConfigsBlock = /signingConfigs\s*\{\s*debug\s*\{([^}]*)\}\s*\}/;
        const replacement = `signingConfigs {
        debug {$1}
        release {
            // Real values live in android/gradle.properties (gitignored,
            // never committed). If they're missing, fail loudly instead of
            // silently falling back to debug signing -- a debug-signed AAB
            // gets rejected by Play Console anyway, so better to know now.
            if (project.hasProperty('AYUXA_RELEASE_STORE_PASSWORD') && AYUXA_RELEASE_STORE_PASSWORD) {
                storeFile file(AYUXA_RELEASE_STORE_FILE)
                storePassword AYUXA_RELEASE_STORE_PASSWORD
                keyAlias AYUXA_RELEASE_KEY_ALIAS
                keyPassword AYUXA_RELEASE_KEY_PASSWORD
            } else {
                throw new GradleException(
                    "Release signing not configured. Fill in AYUXA_RELEASE_STORE_PASSWORD and " +
                    "AYUXA_RELEASE_KEY_PASSWORD in android/gradle.properties (see the keystore " +
                    "generated at android/app/ayuxa-release.keystore)."
                )
            }
        }
    }`;

        if (signingConfigsBlock.test(contents)) {
            config.modResults.contents = contents.replace(signingConfigsBlock, replacement);
        }

        // Point the `release` BUILD TYPE's signingConfig at the new signing
        // config -- not to be confused with the `signingConfigs { debug {...} }`
        // block just replaced above, which also contains the literal text
        // "signingConfigs.debug". Anchored on the stock RN template's own
        // "Caution!" comment (which sits between `release {` and the
        // signingConfig line, breaking a simpler \s*-based match) so this
        // only touches buildTypes.release, never signingConfigs.debug itself.
        // Fallback pattern (looser) in case that comment text ever shifts in
        // a future Expo/RN template -- and if NEITHER matches, fail the
        // build loudly rather than silently ship a debug-signed release.
        const primaryPattern = /(\/\/ Caution! In production, you need to generate your own keystore file\.\s*\/\/ see https:\/\/reactnative\.dev\/docs\/signed-apk-android\.\s*)signingConfig signingConfigs\.debug/;
        const fallbackPattern = /(buildTypes\s*\{[\s\S]*?release\s*\{\s*(?:\/\/[^\n]*\n\s*)*)signingConfig signingConfigs\.debug/;

        let updated = config.modResults.contents;
        if (primaryPattern.test(updated)) {
            updated = updated.replace(primaryPattern, '$1signingConfig signingConfigs.release');
        } else if (fallbackPattern.test(updated)) {
            updated = updated.replace(fallbackPattern, '$1signingConfig signingConfigs.release');
        } else {
            throw new Error(
                'withAndroidHardening: could not find buildTypes.release.signingConfig in app/build.gradle ' +
                'to point at the release keystore. The release build type is still signed with the debug ' +
                'keystore, which Play Store will reject. The build.gradle template has likely changed -- ' +
                'update the regex in plugins/withAndroidHardening.js.'
            );
        }
        config.modResults.contents = updated;

        return config;
    });
};

const withNetworkSecurityConfigFile = (config) => {
    return withDangerousMod(config, [
        'android',
        async (config) => {
            const mainXmlDir = path.join(config.modRequest.platformProjectRoot, 'app/src/main/res/xml');
            fs.mkdirSync(mainXmlDir, { recursive: true });
            fs.writeFileSync(path.join(mainXmlDir, 'network_security_config.xml'), NETWORK_SECURITY_CONFIG_XML);

            const debugXmlDir = path.join(config.modRequest.platformProjectRoot, 'app/src/debug/res/xml');
            fs.mkdirSync(debugXmlDir, { recursive: true });
            fs.writeFileSync(path.join(debugXmlDir, 'network_security_config.xml'), NETWORK_SECURITY_CONFIG_DEBUG_XML);

            return config;
        },
    ]);
};

const withNetworkSecurityConfigManifest = (config) => {
    return withAndroidManifest(config, (config) => {
        const application = config.modResults.manifest.application?.[0];
        if (application) {
            application.$['android:networkSecurityConfig'] = '@xml/network_security_config';
        }
        return config;
    });
};

// expo-image-picker's own AndroidManifest.xml unconditionally declares
// READ_MEDIA_IMAGES/READ_MEDIA_VIDEO, even though launchImageLibraryAsync()
// uses Android's system Photo Picker and never actually requests either at
// runtime -- the app doesn't call requestMediaLibraryPermissionsAsync()
// anywhere. Google Play's photo/video permissions policy flags the mere
// declaration regardless of whether it's ever requested, so force-remove
// both here (manifest merger honors tools:node="remove" from the app
// module over a library's own declaration).
const withRemoveMediaLibraryPermissions = (config) => {
    return withAndroidManifest(config, (config) => {
        const manifest = config.modResults.manifest;
        manifest['uses-permission'] = manifest['uses-permission'] || [];
        for (const name of ['android.permission.READ_MEDIA_IMAGES', 'android.permission.READ_MEDIA_VIDEO']) {
            const already = manifest['uses-permission'].some((p) => p.$?.['android:name'] === name);
            if (!already) {
                manifest['uses-permission'].push({ $: { 'android:name': name, 'tools:node': 'remove' } });
            }
        }
        return config;
    });
};

// expo-screen-capture's usePreventScreenCapture() sets FLAG_SECURE from a
// React useEffect, which only runs after JS boots and the root layout
// mounts -- leaving a real (if brief) native-boot window where FLAG_SECURE
// isn't set yet. Setting it directly in onCreate(), before super.onCreate()
// even runs, closes that window completely: the window is marked secure
// before Activity creation finishes, so there is no frame at any point,
// including the splash screen, where capture is possible on Android.
// Idempotent against a clean `expo prebuild` regenerating this file, same
// as every other mod in this plugin.
const withMainActivitySecureFlag = (config) => {
    return withMainActivity(config, (config) => {
        const contents = config.modResults.contents;
        if (contents.includes('FLAG_SECURE')) return config; // already applied

        const isKotlin = config.modResults.language === 'kt';
        const importLine = isKotlin ? 'import android.view.WindowManager\n' : 'import android.view.WindowManager;\n';
        const flagLine = isKotlin
            ? '    window.setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE)\n'
            : '    getWindow().setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE);\n';

        let updated = contents;
        if (!updated.includes('import android.view.WindowManager')) {
            updated = updated.replace(/^(package [^\n]+\n)/, `$1${importLine}`);
        }

        const onCreatePattern = isKotlin
            ? /(override fun onCreate\(savedInstanceState: Bundle\?\)\s*\{\n)/
            : /(protected void onCreate\(Bundle savedInstanceState\)\s*\{\n)/;

        if (!onCreatePattern.test(updated)) {
            throw new Error(
                'withAndroidHardening: could not find onCreate() in MainActivity to set FLAG_SECURE. ' +
                'The Expo template has likely changed -- update the regex in plugins/withAndroidHardening.js.'
            );
        }
        updated = updated.replace(onCreatePattern, `$1${flagLine}`);

        config.modResults.contents = updated;
        return config;
    });
};

module.exports = function withAndroidHardening(config) {
    config = withGradleJvmMemory(config);
    config = withReleaseSigningProperties(config);
    config = withReleaseSigningConfig(config);
    config = withNetworkSecurityConfigFile(config);
    config = withNetworkSecurityConfigManifest(config);
    config = withRemoveMediaLibraryPermissions(config);
    config = withReleaseOptimization(config);
    config = withRazorpayProguardRules(config);
    config = withMainActivitySecureFlag(config);
    return config;
};
