// Local config plugin bundling three native Android changes that have no
// first-party Expo plugin coverage. android/ is gitignored (regenerated by
// `expo prebuild`), so anything hand-edited there directly is invisible to
// git and gets silently wiped on a clean prebuild — this plugin is what
// makes these survive that regeneration.
//
// Covers:
//   1. Gradle JVM heap/metaspace — fixes an OutOfMemoryError during
//      release Kotlin/KSP compilation (assembleRelease/bundleRelease).
//   2. Release signing config — points `release` build type at the real
//      release keystore instead of the stock debug keystore (Play Store
//      rejects debug-signed AABs outright). Passwords are read from
//      android/gradle.properties (gitignored, filled in locally — see
//      that file's AYUXA_RELEASE_* keys) so no secret lives in this repo.
//   3. Network Security Config — SSL pinning for the app's own backend
//      (api.ayuxacare.com) only. See network_security_config.xml's own
//      header comment for why it's pinned at the CA/root level rather
//      than the leaf cert, and why there is deliberately NO runtime
//      kill-switch (Android bakes this into the APK at build time).
const fs = require('fs');
const path = require('path');
const { withGradleProperties, withAppBuildGradle, withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');

const NETWORK_SECURITY_CONFIG_XML = `<?xml version="1.0" encoding="utf-8"?>
<!--
  SSL pinning for the app's own backend only (api.ayuxacare.com).
  Deliberately scoped to root-CA-level pins (ISRG Root X1/X2, Let's
  Encrypt's trust anchors) rather than the leaf certificate, since the
  leaf rotates every ~60-90 days and would require an app release on
  every renewal otherwise. Two pins are listed so a routine CA-level
  change (which is rare, unlike leaf rotation) doesn't break the app if
  Let's Encrypt shifts primary root.

  Every other domain the app talks to (Google Maps, Firebase, Razorpay,
  Cloudflare's own asset CDN, etc.) is intentionally NOT pinned here —
  those are separate services whose certificate rotation this app does
  not control, and pinning them would only add risk without benefit.

  Note the explicit <base-config cleartextTrafficPermitted="true">: a
  network_security_config.xml existing at all makes Android's IMPLICIT
  base config default cleartextTrafficPermitted to false on API 28+,
  regardless of the manifest's usesCleartextTraffic flag — without this,
  a RELEASE build (which doesn't get the src/debug override below) would
  silently break any legitimate http:// call the app makes. Pinning only
  applies within the domain-config below; this base default is otherwise
  unchanged from stock Android behavior on older API levels.

  expiration is set ~9 months out (well past this cert's Oct 2026 leaf
  renewal, which doesn't affect this root-level pin anyway) as a safety
  valve: if this file is never revisited, pinning silently STOPS being
  enforced after this date rather than silently locking out every user
  forever on a stale pin nobody remembers to update.

  IMPORTANT: there is no runtime kill-switch for this — Android bakes
  this file into the APK at build time. The only way to change or
  disable it is a new app release. See MVP_LAUNCH_PLAN.md §Phase 3 (C-03)
  before ever touching this file again.
-->
<network-security-config>
    <base-config cleartextTrafficPermitted="true" />
    <domain-config>
        <domain includeSubdomains="false">api.ayuxacare.com</domain>
        <pin-set expiration="2027-06-01">
            <!-- ISRG Root X1: Let's Encrypt's primary trust anchor -->
            <pin digest="SHA-256">C5+lpZ7tcVwmwQIMcRtPbsQtWLABXhQzejna0wHFr8M=</pin>
            <!-- ISRG Root X2: backup pin, actually served in the live chain -->
            <pin digest="SHA-256">diGVwiVYbubAI3RW4hB9xU8e/CH2GnkuvVFZE8zmgzI=</pin>
        </pin-set>
    </domain-config>
</network-security-config>
`;

// Debug builds additionally need to reach the local Metro dev server over
// plain http:// on a LAN IP (e.g. 10.x.x.x) — cleartextTrafficPermitted
// alone doesn't scope pinning away from that traffic, it just allows
// cleartext in general (which debug builds already need for Metro
// regardless of pinning). Resource merging prefers this debug-variant file
// over the main one automatically, same as the existing
// android:usesCleartextTraffic override in src/debug/AndroidManifest.xml.
const NETWORK_SECURITY_CONFIG_DEBUG_XML = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Debug-only override: no pinning at all, cleartext allowed everywhere.
  This file is NEVER included in a release build (Android resource
  merging: src/debug/res only applies to the debug variant) — see the
  main network_security_config.xml for the real production config.
-->
<network-security-config>
    <base-config cleartextTrafficPermitted="true" />
</network-security-config>
`;

const setGradleProperty = (modResults, key, value) => {
    const existing = modResults.find((item) => item.type === 'property' && item.key === key);
    if (existing) {
        existing.value = value;
    } else {
        modResults.push({ type: 'property', key, value });
    }
};

const withGradleJvmMemory = (config) => {
    return withGradleProperties(config, (config) => {
        setGradleProperty(config.modResults, 'org.gradle.jvmargs', '-Xmx4096m -XX:MaxMetaspaceSize=1024m');
        return config;
    });
};

// android/gradle.properties is fully regenerated on every `expo prebuild`,
// so storing the release keystore passwords there directly means they get
// silently wiped on every clean prebuild. Reading them from env vars here
// (same pattern as EXPO_PUBLIC_GOOGLE_MAPS_API_KEY elsewhere in this repo)
// means one entry in .env / an EAS secret survives every regeneration
// automatically -- nothing to remember to re-type.
const withReleaseSigningProperties = (config) => {
    return withGradleProperties(config, (config) => {
        setGradleProperty(config.modResults, 'AYUXA_RELEASE_STORE_FILE', 'ayuxa-release.keystore');
        setGradleProperty(config.modResults, 'AYUXA_RELEASE_KEY_ALIAS', 'ayuxa-release');
        setGradleProperty(config.modResults, 'AYUXA_RELEASE_STORE_PASSWORD', process.env.RELEASE_KEYSTORE_PASSWORD || '');
        setGradleProperty(config.modResults, 'AYUXA_RELEASE_KEY_PASSWORD', process.env.RELEASE_KEY_PASSWORD || '');
        return config;
    });
};

const withReleaseSigningConfig = (config) => {
    return withAppBuildGradle(config, (config) => {
        const contents = config.modResults.contents;
        if (contents.includes('AYUXA_RELEASE_STORE_PASSWORD')) return config; // already applied

        const signingConfigsBlock = /signingConfigs\s*\{\s*debug\s*\{([^}]*)\}\s*\}/;
        const replacement = `signingConfigs {
        debug {$1}
        release {
            // Real values live in android/gradle.properties (gitignored,
            // never committed). If they're missing, fail loudly instead of
            // silently falling back to debug signing -- a debug-signed AAB
            // gets rejected by Play Console anyway, so better to know now.
            if (project.hasProperty('AYUXA_RELEASE_STORE_PASSWORD') && AYUXA_RELEASE_STORE_PASSWORD) {
                storeFile file(AYUXA_RELEASE_STORE_FILE)
                storePassword AYUXA_RELEASE_STORE_PASSWORD
                keyAlias AYUXA_RELEASE_KEY_ALIAS
                keyPassword AYUXA_RELEASE_KEY_PASSWORD
            } else {
                throw new GradleException(
                    "Release signing not configured. Fill in AYUXA_RELEASE_STORE_PASSWORD and " +
                    "AYUXA_RELEASE_KEY_PASSWORD in android/gradle.properties (see the keystore " +
                    "generated at android/app/ayuxa-release.keystore)."
                )
            }
        }
    }`;

        if (signingConfigsBlock.test(contents)) {
            config.modResults.contents = contents.replace(signingConfigsBlock, replacement);
        }

        // Point the `release` BUILD TYPE's signingConfig at the new signing
        // config -- not to be confused with the `signingConfigs { debug {...} }`
        // block just replaced above, which also contains the literal text
        // "signingConfigs.debug". Anchored on the stock RN template's own
        // "Caution!" comment (which sits between `release {` and the
        // signingConfig line, breaking a simpler \s*-based match) so this
        // only touches buildTypes.release, never signingConfigs.debug itself.
        // Fallback pattern (looser) in case that comment text ever shifts in
        // a future Expo/RN template -- and if NEITHER matches, fail the
        // build loudly rather than silently ship a debug-signed release.
        const primaryPattern = /(\/\/ Caution! In production, you need to generate your own keystore file\.\s*\/\/ see https:\/\/reactnative\.dev\/docs\/signed-apk-android\.\s*)signingConfig signingConfigs\.debug/;
        const fallbackPattern = /(buildTypes\s*\{[\s\S]*?release\s*\{\s*(?:\/\/[^\n]*\n\s*)*)signingConfig signingConfigs\.debug/;

        let updated = config.modResults.contents;
        if (primaryPattern.test(updated)) {
            updated = updated.replace(primaryPattern, '$1signingConfig signingConfigs.release');
        } else if (fallbackPattern.test(updated)) {
            updated = updated.replace(fallbackPattern, '$1signingConfig signingConfigs.release');
        } else {
            throw new Error(
                'withAndroidHardening: could not find buildTypes.release.signingConfig in app/build.gradle ' +
                'to point at the release keystore. The release build type is still signed with the debug ' +
                'keystore, which Play Store will reject. The build.gradle template has likely changed -- ' +
                'update the regex in plugins/withAndroidHardening.js.'
            );
        }
        config.modResults.contents = updated;

        return config;
    });
};

const withNetworkSecurityConfigFile = (config) => {
    return withDangerousMod(config, [
        'android',
        async (config) => {
            const mainXmlDir = path.join(config.modRequest.platformProjectRoot, 'app/src/main/res/xml');
            fs.mkdirSync(mainXmlDir, { recursive: true });
            fs.writeFileSync(path.join(mainXmlDir, 'network_security_config.xml'), NETWORK_SECURITY_CONFIG_XML);

            const debugXmlDir = path.join(config.modRequest.platformProjectRoot, 'app/src/debug/res/xml');
            fs.mkdirSync(debugXmlDir, { recursive: true });
            fs.writeFileSync(path.join(debugXmlDir, 'network_security_config.xml'), NETWORK_SECURITY_CONFIG_DEBUG_XML);

            return config;
        },
    ]);
};

const withNetworkSecurityConfigManifest = (config) => {
    return withAndroidManifest(config, (config) => {
        const application = config.modResults.manifest.application?.[0];
        if (application) {
            application.$['android:networkSecurityConfig'] = '@xml/network_security_config';
        }
        return config;
    });
};

module.exports = function withAndroidHardening(config) {
    config = withGradleJvmMemory(config);
    config = withReleaseSigningProperties(config);
    config = withReleaseSigningConfig(config);
    config = withNetworkSecurityConfigFile(config);
    config = withNetworkSecurityConfigManifest(config);
    return config;
};
