const fs = require('fs');
const path = require('path');

const localesDir = 'd:/codes/MERN/medico/mobile/i18n/locales';

const translations = {
    en: {
        pricing_a: "₹299 Service Charge + Vendor Bill",
        pricing_b: "₹299 Service Charge (Max 2 Bills)",
        pricing_c_online: "₹499 (Online Video Call)",
        pricing_c_visit: "₹999 (Home Visit)",
        pricing_d: "Zero Service Charge (Inquiry)",
        comments_required: "Please enter comments or details of your request.",
        address_required: "Please provide a valid address.",
        date_required: "Please select a date and time slot.",
        invalid_time: "Please select a future date and time.",
        bill_photo_required: "Please upload a photo of the bills.",
        request_submitted: "Your request has been successfully submitted!",
        bullet_homemaker: "Covered under Homemaker subscription plan benefits",
        bullet_professional: "Certified, verified, and safe professionals",
        bullet_support: "24/7 dedicated support tracking",
        home_essentials: "Home Essentials",
        delivery_method: "Delivery Method",
        online_call: "Online Video Call (₹499)",
        home_visit: "Home Visit (₹999)",
        comments: "Comments / Requirements",
        comments_placeholder: "Describe your requirements or any instructions here...",
        upload_bill_photos: "Upload Bill Copies",
        upload_optional_photos: "Upload Photos (Optional)",
        image_upload_subtitle: "JPG, PNG up to 10MB"
    },
    hi: {
        pricing_a: "₹299 सेवा शुल्क + विक्रेता बिल",
        pricing_b: "₹299 सेवा शुल्क (अधिकतम 2 बिल)",
        pricing_c_online: "₹499 (ऑनलाइन वीडियो कॉल)",
        pricing_c_visit: "₹999 (गृह दौरा)",
        pricing_d: "शून्य सेवा शुल्क (पूछताछ)",
        comments_required: "कृपया अपने अनुरोध की टिप्पणी या विवरण दर्ज करें।",
        address_required: "कृपया एक वैध पता प्रदान करें।",
        date_required: "कृपया तिथि और समय स्लॉट चुनें।",
        invalid_time: "कृपया भविष्य की तिथि और समय चुनें।",
        bill_photo_required: "कृपया बिलों की एक फोटो अपलोड करें।",
        request_submitted: "आपका अनुरोध सफलतापूर्वक सबमिट कर दिया गया है!",
        bullet_homemaker: "होममेकर सदस्यता योजना के लाभों के तहत कवर किया गया",
        bullet_professional: "प्रमाणित, सत्यापित और सुरक्षित पेशेवर",
        bullet_support: "24/7 समर्पित सहायता ट्रैकिंग",
        home_essentials: "होम एसेंशियल",
        delivery_method: "वितरण का तरीका",
        online_call: "ऑनलाइन वीडियो कॉल (₹499)",
        home_visit: "गृह दौरा (₹999)",
        comments: "टिप्पणियाँ / आवश्यकताएं",
        comments_placeholder: "अपनी आवश्यकताएं या कोई निर्देश यहां लिखें...",
        upload_bill_photos: "बिल की प्रतियां अपलोड करें",
        upload_optional_photos: "फोटो अपलोड करें (वैकल्पिक)",
        image_upload_subtitle: "10MB तक की JPG, PNG"
    },
    kn: {
        pricing_a: "₹299 ಸೇವಾ ಶುಲ್ಕ + ಮಾರಾಟಗಾರರ ಬಿಲ್",
        pricing_b: "₹299 ಸೇವಾ ಶುಲ್ಕ (ಗರಿಷ್ಠ 2 ಬಿಲ್‌ಗಳು)",
        pricing_c_online: "₹499 (ಆನ್‌ಲೈನ್ ವಿಡಿಯೋ ಕರೆ)",
        pricing_c_visit: "₹999 (ಮನೆ ಭೇಟಿ)",
        pricing_d: "ಶೂನ್ಯ ಸೇವಾ ಶುಲ್ಕ (ವಿಚಾರಣೆ)",
        comments_required: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ವಿನಂತಿಯ ಕಾಮೆಂಟ್‌ಗಳು ಅಥವಾ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ.",
        address_required: "ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ ವಿಳಾಸವನ್ನು ಒದಗಿಸಿ.",
        date_required: "ದಯವಿಟ್ಟು ದಿನಾಂಕ ಮತ್ತು ಸಮಯದ ಸ್ಲಾಟ್ ಆಯ್ಕೆಮಾಡಿ.",
        invalid_time: "ದಯವಿಟ್ಟು ಭವಿಷ್ಯದ ದಿನಾಂక ಮತ್ತು ಸಮಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
        bill_photo_required: "ದಯವಿಟ್ಟು ಬಿಲ್‌ಗಳ ಫೋಟೋವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
        request_submitted: "ನಿಮ್ಮ ವಿನಂತಿಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ!",
        bullet_homemaker: "ಹೋಮ್ ಮೇಕರ್ ಚಂದಾದಾರಿಕೆ ಯೋಜನೆಯ ಪ್ರಯೋಜನಗಳ ಅಡಿಯಲ್ಲಿ ಒಳಪಡುತ್ತದೆ",
        bullet_professional: "ಪ್ರಮಾಣೀಕೃತ, ಪರಿಶೀಲಿಸಿದ ಮತ್ತು ಸುರಕ್ಷಿತ ವೃತ್ತಿపರರು",
        bullet_support: "24/7 ಸಮರ್ಪಿತ ಬೆಂಬಲ ಟ್ರ್ಯಾಕಿಂಗ್",
        home_essentials: "ಮನೆಯ ಅಗತ್ಯಗಳು",
        delivery_method: "ವಿತರಣಾ ವಿಧಾನ",
        online_call: "ಆನ್‌ಲೈನ್ ವಿಡಿಯೋ ಕರೆ (₹499)",
        home_visit: "ಮನೆ ಭೇಟಿ (₹999)",
        comments: "ಕಾಮೆಂಟ್‌ಗಳು / ಅಗತ್ಯತೆಗಳು",
        comments_placeholder: "ನಿಮ್ಮ ಅಗತ್ಯತೆಗಳು ಅಥವಾ ಯಾವುದೇ ಸೂಚನೆಗಳನ್ನು ಇಲ್ಲಿ ವಿವರಿಸಿ...",
        upload_bill_photos: "ಬಿಲ್ ಪ್ರತಿಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
        upload_optional_photos: "ಫೋಟೋಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ (ಐಚ್ಛಿಕ)",
        image_upload_subtitle: "10MB ವರೆಗಿನ JPG, PNG"
    },
    ta: {
        pricing_a: "₹299 சேவை கட்டணம் + விற்பனையாளர் பில்",
        pricing_b: "₹299 சேவை கட்டணம் (அதிகபட்சம் 2 பில்கள்)",
        pricing_c_online: "₹499 (ஆன்லைன் வீடியோ அழைப்பு)",
        pricing_c_visit: "₹999 (வீட்டு வருகை)",
        pricing_d: "பூஜ்ஜிய சேவை கட்டணம் (விசாரணை)",
        comments_required: "தயவுசெய்து உங்கள் கோரிக்கையின் கருத்துகள் அல்லது விவரங்களை உள்ளிடவும்.",
        address_required: "தயவுசெய்து சரியான முகவரியை வழங்கவும்.",
        date_required: "தயவுசெய்து தேதி மற்றும் நேரத்தை தேர்வு செய்யவும்.",
        invalid_time: "தயவுசெய்து எதிர்கால தேதி மற்றும் நேரத்தை தேர்வு செய்யவும்.",
        bill_photo_required: "தயவுசெய்து பில்களின் புகைப்படத்தை பதிவேற்றவும்.",
        request_submitted: "உங்கள் கோரிக்கை வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!",
        bullet_homemaker: "ஹோம்மேக்கர் சந்தா திட்ட நன்மைகளின் கீழ் உள்ளடங்கும்",
        bullet_professional: "சான்றளிக்கப்பட்ட, சரிபார்க்கப்பட்ட மற்றும் பாதுகாப்பான நிपुணர்கள்",
        bullet_support: "24/7 பிரத்யேக ஆதரவு கண்காணிப்பு",
        home_essentials: "வீட்டு அத்தியாவசிய பொருட்கள்",
        delivery_method: "வழங்கும் முறை",
        online_call: "ஆன்லைன் வீடியோ அழைப்பு (₹499)",
        home_visit: "வீட்டு வருகை (₹999)",
        comments: "கருத்துகள் / தேவைகள்",
        comments_placeholder: "உங்கள் தேவைகள் அல்லது ஏதேனும் வழிமுறைகளை இங்கே விவரிக்கவும்...",
        upload_bill_photos: "பில் நகல்களைப் பதிவேற்றவும்",
        upload_optional_photos: "புகைப்படங்களை பதிவேற்றவும் (விருப்பத்தேர்வு)",
        image_upload_subtitle: "10MB வரையிலான JPG, PNG"
    },
    te: {
        pricing_a: "₹299 సేవా రుసుము + విక్రేత బిల్లు",
        pricing_b: "₹299 సేవా రుసుము (గరిష్టంగా 2 బిల్లులు)",
        pricing_c_online: "₹499 (ఆన్‌లైన్ వీడియో కాల్)",
        pricing_c_visit: "₹999 (ఇంటి సందర్శన)",
        pricing_d: "సున్నా సేవా రుసుము (విచారణ)",
        comments_required: "దయచేసి మీ అభ్యర్థన యొక్క వ్యాఖ్యలు లేదా వివరాలను నమోదు చేయండి.",
        address_required: "దయచేసి చెల్లుబాటు అయ్యే చిరునామాను అందించండి.",
        date_required: "దయచేసి తేదీ మరియు సమయ స్లాట్‌ను ఎంచుకోండి.",
        invalid_time: "దయచేసి భవిష్యత్తు తేదీ మరియు సమయాన్ని ఎంచుకోండి.",
        bill_photo_required: "దయచేసి బిల్లుల ఫోటోను అప్‌లోడ్ చేయండి.",
        request_submitted: "మీ అభ్యర్థన విజయవంతంగా సమర్పించబడింది!",
        bullet_homemaker: "హోమ్‌మేకర్ సభ్యత్వ ప్లాన్ ప్రయోజనాల కింద కవర్ చేయబడుతుంది",
        bullet_professional: "ధృవీకరించబడిన, సురక్షితమైన మరియు నిపుణులైన సిబ్బంది",
        bullet_support: "24/7 అంకితమైన మద్దతు ట్రాకింగ్",
        home_essentials: "ఇంటి అవసరాలు",
        delivery_method: "డెలివరీ పద్ధతి",
        online_call: "ఆన్‌లైన్ వీడియో కాల్ (₹499)",
        home_visit: "ఇంటి సందర్శన (₹999)",
        comments: "వ్యాఖ్యలు / అవసరాలు",
        comments_placeholder: "మీ అవసరాలు లేదా ఏవైనా సూచనలను ఇక్కడ వివరించండి...",
        upload_bill_photos: "బిల్లు కాపీలను అప్‌లోడ్ చేయండి",
        upload_optional_photos: "ఫోటోలను అప్‌లోడ్ చేయండి (ఐచ్ఛికం)",
        image_upload_subtitle: "10MB వరకు JPG, PNG"
    },
    ml: {
        pricing_a: "₹299 സേവന നിരക്ക് + വെണ്ടർ ബിൽ",
        pricing_b: "₹299 സേവന നിരക്ക് (പരമാവധി 2 ബില്ലുകൾ)",
        pricing_c_online: "₹499 (ഓൺലൈൻ വീഡിയോ കോൾ)",
        pricing_c_visit: "₹999 (ഹോം വിസിറ്റ്)",
        pricing_d: "പൂജ്യം സേവന നിരക്ക് (അന്വേഷണം)",
        comments_required: "ദയവായി നിങ്ങളുടെ അഭ്യർത്ഥനയുടെ വിവരങ്ങൾ അല്ലെങ്കിൽ അഭിപ്രായങ്ങൾ നൽകുക.",
        address_required: "ദയവായി സാധുവായ ഒരു വിലാസം നൽകുക.",
        date_required: "ദയവായി തീയതിയും സമയവും തിരഞ്ഞെടുക്കുക.",
        invalid_time: "ദയവായി ഭാവിയിലെ തീയതിയും സമയവും തിരഞ്ഞെടുക്കുക.",
        bill_photo_required: "ദയവായി ബില്ലുകളുടെ ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക.",
        request_submitted: "നിങ്ങളുടെ അഭ്യർത്ഥന വിജയകരമായി സമർപ്പിച്ചു!",
        bullet_homemaker: "ഹോംമേക്കർ സബ്‌സ്‌ക്രിപ്ഷൻ പ്ലാൻ ആനുകൂല്യങ്ങളിൽ ഉൾപ്പെടുന്നു",
        bullet_professional: "സാക്ഷ്യപ്പെടുത്തിയതും സുരക്ഷിതവുമായ വിദഗ്ദ്ധർ",
        bullet_support: "24/7 സമർപ്പിത പിന്തുണ ട്രാക്കിംഗ്",
        home_essentials: "വീട്ടു ആവശ്യങ്ങൾ",
        delivery_method: "ഡെലിവറി രീതി",
        online_call: "ഓൺലൈൻ വീഡിയോ കോൾ (₹499)",
        home_visit: "ഹോം വിസിറ്റ് (₹999)",
        comments: "അഭിപ്രായങ്ങൾ / ആവശ്യങ്ങൾ",
        comments_placeholder: "നിങ്ങളുടെ ആവശ്യങ്ങൾ അല്ലെങ്കിൽ നിർദ്ദേശങ്ങൾ ഇവിടെ വിവരിക്കുക...",
        upload_bill_photos: "ബിൽ കോപ്പികൾ അപ്‌ലോഡ് ചെയ്യുക",
        upload_optional_photos: "ഫോട്ടോകൾ അപ്‌ലോഡ് ചെയ്യുക (ഓപ്ഷണൽ)",
        image_upload_subtitle: "10MB വരെയുള്ള JPG, PNG"
    },
    mr: {
        pricing_a: "₹299 सेवा शुल्क + विक्रेता बिल",
        pricing_b: "₹299 सेवा शुल्क (जास्तीत जास्त 2 बिले)",
        pricing_c_online: "₹499 (ऑनलाइन व्हिडिओ कॉल)",
        pricing_c_visit: "₹999 (घर भेट)",
        pricing_d: "शून्य सेवा शुल्क (चौकशी)",
        comments_required: "कृपया आपल्या विनंतीची टिप्पणी किंवा तपशील प्रविष्ट करा.",
        address_required: "कृपया वैध पत्ता प्रदान करा.",
        date_required: "कृपया तारीख आणि वेळ स्लॉट निवडा.",
        invalid_time: "कृपया भविष्यातील तारीख आणि वेळ निवडा.",
        bill_photo_required: "कृपया बिलांचा फोटो अपलोड करा.",
        request_submitted: "तुमची विनंती यशस्वीरित्या सबमिट केली गेली आहे!",
        bullet_homemaker: "होममेकर सदस्यता योजनेच्या फायद्यांतर्गत समाविष्ट",
        bullet_professional: "प्रमाणित, सत्यापित आणि सुरक्षित व्यावसायिक",
        bullet_support: "24/7 समर्पित समर्थन ट्रॅकिंग",
        home_essentials: "घरगुती आवश्यक गोष्टी",
        delivery_method: "डिलिव्हरी पद्धत",
        online_call: "ऑनलाइन व्हिडिओ कॉल (₹499)",
        home_visit: "घर भेट (₹999)",
        comments: "अभिप्राय / आवश्यकता",
        comments_placeholder: "आपल्या आवश्यकता किंवा काही सूचना येथे लिहा...",
        upload_bill_photos: "बिलांच्या प्रती अपलोड करा",
        upload_optional_photos: "फोटो अपलोड करा (पर्यायी)",
        image_upload_subtitle: "10MB पर्यंतचे JPG, PNG"
    },
    bn: {
        pricing_a: "₹299 পরিষেবা চার্জ + বিক্রেতা বিল",
        pricing_b: "₹299 পরিষেবা চার্জ (সর্বাধিক 2 টি বিল)",
        pricing_c_online: "₹499 (অনলাইন ভিডিও কল)",
        pricing_c_visit: "₹999 (হোম ভিজিট)",
        pricing_d: "শূন্য পরিষেবা চার্জ (অনুসন্ধান)",
        comments_required: "দয়া করে আপনার অনুরোধের মন্তব্য বা বিবরণ লিখুন।",
        address_required: "দয়া করে একটি বৈধ ঠিকানা দিন।",
        date_required: "দয়া করে তারিখ এবং সময় স্লট নির্বাচন করুন।",
        invalid_time: "দয়া করে ভবিষ্যতের একটি তারিখ এবং সময় নির্বাচন করুন।",
        bill_photo_required: "দয়া করে বিলের একটি ছবি আপলোড করুন।",
        request_submitted: "আপনার অনুরোধ সফলভাবে জমা দেওয়া হয়েছে!",
        bullet_homemaker: "হোমমেকার সাবস্ক্রিপশন প্ল্যানের সুবিধার অধীনে অন্তর্ভুক্ত",
        bullet_professional: "প্রত্যয়িত, যাচাইকৃত এবং নিরাপদ পেশাদার",
        bullet_support: "24/7 ডেডিকেটেড সহায়তা ট্র্যাকিং",
        home_essentials: "গৃহস্থালীর প্রয়োজনীয় জিনিসপত্র",
        delivery_method: "ডেলিভারি পদ্ধতি",
        online_call: "অনলাইন ভিডিও কল (অনলাইন কল) (₹499)",
        home_visit: "হোম ভিজিট (₹999)",
        comments: "মন্তব্য / প্রয়োজনীয়তা",
        comments_placeholder: "আপনার প্রয়োজনীয়তা বা কোনো নির্দেশনা এখানে লিখুন...",
        upload_bill_photos: "বিলের কপি আপলোড করুন",
        upload_optional_photos: "ছবি আপলোড করুন (ঐচ্ছিক)",
        image_upload_subtitle: "10MB পর্যন্ত JPG, PNG"
    }
};

for (const lang of Object.keys(translations)) {
    const filePath = path.join(localesDir, `${lang}.json`);
    if (fs.existsSync(filePath)) {
        try {
            const fileContent = fs.readFileSync(filePath, 'utf8');
            const json = JSON.parse(fileContent);
            json.service_detail = translations[lang];
            fs.writeFileSync(filePath, JSON.stringify(json, null, 4), 'utf8');
            console.log(`Synced ${lang}.json successfully.`);
        } catch (e) {
            console.error(`Failed to process ${lang}.json:`, e);
        }
    } else {
        console.warn(`${filePath} does not exist.`);
    }
}
