const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, 'i18n', 'locales');
const languages = ['en', 'hi', 'kn', 'ta', 'te', 'ml', 'mr', 'bn'];

const newKeys = {
  en: {
    "care_super_title": "Value Plans for Peace of Mind",
    "care_subtitle_1": "Your health is our priority.",
    "care_subtitle_2": "Next-gen care, human touch.",
    "care_subtitle_3": "Elder care, peace of mind.",
    "home_super_title": "Empower Independent Living",
    "home_title": "Home Essential Plan",
    "value_plans_subtitle": "Value plans for peace of mind",
    "active_plan_banner": "Active Plan",
    "current_plan": "✓ Current Plan",
    "already_subscribed": "Already Subscribed",
    "subscribe_now": "Subscribe Now",
    "per_cycle": "per {{suffix}}",
    "days_suffix": "{{days}} days",
    "home_disclaimer": "Note: Only Ayuxa service charges are waived. Vendor charges, spare parts, and other third-party costs are payable by the client.",
    "on_demand": "ON DEMAND",
    "transit_care_title": "Ayuxa Transit Care",
    "transit_care_subtitle": "Get medical accompaniment, spiritual escort, or leisure travels with fully trained caregivers.",
    "pay_per_trip": "Pay per trip",
    "request_now": "Request Now",
    "why_ayuxa": "Why Ayuxa?",
    "my_memberships": "My Memberships",
    "manage_plans": "View, renew, and manage your plans",
    "plan_usage_policy": "Plan Usage Policy",
    "policy_content": "Monthly and quarterly benefits operate on a use-it-or-lose-it basis. Unused visits and entitlements do not roll over to the next billing cycle.",
    "terms_conditions_title": "Terms & Conditions",
    "medical_transit_title": "Medical Transit (Out of State)",
    "spiritual_leisure_title": "Spiritual & Leisure Journeys",
    "transit_feat_booking": "End-to-End Booking: Flights, trains, hotels, and local cabs.",
    "transit_feat_companion": "Transit Companion: Caregiver handles travel, luggage, and wheelchair support.",
    "transit_feat_dossier": "Medical Dossier: Physical & digital medical file prep for specialists.",
    "transit_feat_coordination": "Destination Coordination: Caregiver stays with elder, assists during visit, updates family.",
    "transit_feat_medication": "Medication Management: Timely reminders & dosage support during transit.",
    "transit_feat_crowd": "Crowd & Mobility: Assistance with priority queues, crowds, and temple seating.",
    "transit_feat_dietary": "Dietary Adherence: Strict maintenance of prescribed diets during travel/events.",
    "transit_feat_itineraries": "Paced Itineraries: Travel planned around comfort with adequate rest.",
    "transit_feat_dest_coordination": "Destination Coordination: Support during events and safe return home."
  },
  hi: {
    "care_super_title": "मन की शांति के लिए वैल्यू प्लान",
    "care_subtitle_1": "आपका स्वास्थ्य हमारी प्राथमिकता है।",
    "care_subtitle_2": "आधुनिक देखभाल, मानवीय स्पर्श।",
    "care_subtitle_3": "बुजुर्गों की देखभाल, मानसिक शांति।",
    "home_super_title": "स्वतंत्र जीवन को सशक्त बनाएं",
    "home_title": "होम एसेंशियल प्लान",
    "value_plans_subtitle": "मन की शांति के लिए वैल्यू प्लान",
    "active_plan_banner": "सक्रिय प्लान",
    "current_plan": "✓ वर्तमान प्लान",
    "already_subscribed": "पहले से सब्सक्राइब किया हुआ है",
    "subscribe_now": "अभी सब्सक्राइब करें",
    "per_cycle": "प्रति {{suffix}}",
    "days_suffix": "{{days}} दिन",
    "home_disclaimer": "नोट: केवल आयुक्सा सेवा शुल्क माफ किए जाते हैं। वेंडर शुल्क, स्पेयर पार्ट्स और अन्य तृतीय-पक्ष लागतें ग्राहक द्वारा देय हैं।",
    "on_demand": "मांग पर",
    "transit_care_title": "आयुक्सा ट्रांजिट केयर",
    "transit_care_subtitle": "पूरी तरह से प्रशिक्षित केयरगिवर के साथ चिकित्सा संगत, आध्यात्मिक एस्कॉर्ट, या अवकाश यात्राएं प्राप्त करें।",
    "pay_per_trip": "प्रति यात्रा भुगतान",
    "request_now": "अभी अनुरोध करें",
    "why_ayuxa": "आयुक्सा क्यों?",
    "my_memberships": "मेरी सदस्यताएं",
    "manage_plans": "अपने प्लान देखें, नवीनीकृत करें और प्रबंधित करें",
    "plan_usage_policy": "प्लान उपयोग नीति",
    "policy_content": "मासिक और त्रैमासिक लाभ उपयोग-या-खो-दें के आधार पर काम करते हैं। अप्रयुक्त दौरे और पात्रताएं अगले बिलिंग चक्र में स्थानांतरित नहीं होती हैं।",
    "terms_conditions_title": "नियम और शर्तें",
    "medical_transit_title": "मेडिकल ट्रांजिट (राज्य से बाहर)",
    "spiritual_leisure_title": "आध्यात्मिक और अवकाश यात्राएं",
    "transit_feat_booking": "शुरू से अंत तक बुकिंग: उड़ानें, ट्रेनें, होटल और स्थानीय कैब।",
    "transit_feat_companion": "पारगमन साथी: केयरगिवर यात्रा, सामान और व्हीलचेयर सहायता संभालता है।",
    "transit_feat_dossier": "मेडिकल डोजियर: विशेषज्ञों के लिए भौतिक और डिजिटल मेडिकल फाइल तैयार करना।",
    "transit_feat_coordination": "गंतव्य समन्वय: केयरगिवर बुजुर्ग के साथ रहता है, यात्रा के दौरान सहायता करता है, परिवार को अपडेट करता है।",
    "transit_feat_medication": "दवा प्रबंधन: पारगमन के दौरान समय पर अनुस्मारक और खुराक सहायता।",
    "transit_feat_crowd": "भीड़ और गतिशीलता: प्राथमिकता कतारों, भीड़ और मंदिर में बैठने की सहायता।",
    "transit_feat_dietary": "आहार अनुपालन: यात्रा/आयोजनों के दौरान निर्धारित आहार का सख्त रखरखाव।",
    "transit_feat_itineraries": "आरामदायक कार्यक्रम: पर्याप्त आराम के साथ आराम के इर्द-गिर्द नियोजित यात्रा।",
    "transit_feat_dest_coordination": "गंतव्य समन्वय: आयोजनों के दौरान सहायता और सुरक्षित घर वापसी।"
  },
  kn: {
    "care_super_title": "ನೆಮ್ಮದಿಗಾಗಿ ಮೌಲ್ಯದ ಯೋಜನೆಗಳು",
    "care_subtitle_1": "ನಿಮ್ಮ ಆರೋಗ್ಯವೇ ನಮ್ಮ ಆದ್ಯತೆ.",
    "care_subtitle_2": "ಮುಂದಿನ ಪೀಳಿಗೆಯ ಆರೈಕೆ, ಮಾನವೀಯ ಸ್ಪರ್ಶ.",
    "care_subtitle_3": "ಹಿರಿಯರ ಆರೈಕೆ, ನೆಮ್ಮದಿ.",
    "home_super_title": "ಸ್ವತಂತ್ರ ಜೀವನವನ್ನು ಸಬಲೀಕರಣಗೊಳಿಸಿ",
    "home_title": "ಹೋಮ್ ಎಸೆನ್ಷಿಯಲ್ ಪ್ಲಾನ್",
    "value_plans_subtitle": "ನೆಮ್ಮದಿಗಾಗಿ ಮೌಲ್ಯದ ಯೋಜನೆಗಳು",
    "active_plan_banner": "ಸಕ್ರಿಯ ಯೋಜನೆ",
    "current_plan": "✓ ಪ್ರಸ್ತುತ ಯೋಜನೆ",
    "already_subscribed": "ಈಗಾಗಲೇ ಚಂದಾದಾರರಾಗಿದ್ದಾರೆ",
    "subscribe_now": "ಈಗ ಚಂದಾದಾರರಾಗಿ",
    "per_cycle": "ಪ್ರತಿ {{suffix}}",
    "days_suffix": "{{days}} ದಿನಗಳು",
    "home_disclaimer": "ಗಮನಿಸಿ: ಆಯುಕ್ಸಾ ಸೇವಾ ಶುಲ್ಕಗಳನ್ನು ಮಾತ್ರ ಮನ್ನಾ ಮಾಡಲಾಗುತ್ತದೆ. ಮಾರಾಟಗಾರರ ಶುಲ್ಕಗಳು, ಬಿಡಿಭಾಗಗಳು ಮತ್ತು ಇತರ ಮೂರನೇ ವ್ಯಕ್ತಿಯ ವೆಚ್ಚಗಳನ್ನು ಕ್ಲೈಂಟ್ ಪಾವತಿಸಬೇಕಾಗುತ್ತದೆ.",
    "on_demand": "ಬೇಡಿಕೆಯ ಮೇರೆಗೆ",
    "transit_care_title": "ಆಯುಕ್ಸಾ ಟ್ರಾನ್ಸಿಟ್ ಕೇರ್",
    "transit_care_subtitle": "ತರಬೇತಿ ಪಡೆದ ಆರೈಕೆದಾರರೊಂದಿಗೆ ವೈದ್ಯಕೀಯ ಬೆಂಬಲ, ಆಧ್ಯಾತ್ಮಿಕ ಬೆಂಗಾವಲು ಅಥವಾ ವಿರಾಮ ಪ್ರಯಾಣಗಳನ್ನು ಪಡೆಯಿರಿ.",
    "pay_per_trip": "ಪ್ರತಿ ಟ್ರಿಪ್‌ಗೆ ಪಾವತಿಸಿ",
    "request_now": "ಈಗ ವಿನಂತಿಸಿ",
    "why_ayuxa": "ಏಕೆ ಆಯುಕ್ಸಾ?",
    "my_memberships": "ನನ್ನ ಸದಸ್ಯತ್ವಗಳು",
    "manage_plans": "ನಿಮ್ಮ ಯೋಜನೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ, ನವೀಕರಿಸಿ ಮತ್ತು ನಿರ್ವಹಿಸಿ",
    "plan_usage_policy": "ಯೋಜನೆ ಬಳಕೆಯ ನೀತಿ",
    "policy_content": "ಮಾಸಿಕ ಮತ್ತು ತ್ರೈಮಾಸಿಕ ಪ್ರಯೋಜನಗಳು ಬಳಸಿ ಅಥವಾ ಕಳೆದುಕೊಳ್ಳಿ ಆಧಾರದ ಮೇಲೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತವೆ. ಬಳಸದ ಭೇಟಿಗಳು ಮುಂದಿನ ಬಿಲ್ಲಿಂಗ್ ಚಕ್ರಕ್ಕೆ ವರ್ಗಾವಣೆಯಾಗುವುದಿಲ್ಲ.",
    "terms_conditions_title": "ನಿಯಮಗಳು ಮತ್ತು ನಿಬಂಧನೆಗಳು",
    "medical_transit_title": "ವೈದ್ಯಕೀಯ ಸಾರಿಗೆ (ರಾಜ್ಯದ ಹೊರಗೆ)",
    "spiritual_leisure_title": "ಆಧ್ಯಾತ್ಮಿಕ ಮತ್ತು ವಿರಾಮ ಪ್ರಯಾಣಗಳು",
    "transit_feat_booking": "ಕೊನೆಯಿಂದ ಕೊನೆಯವರೆಗೆ ಬುಕಿಂಗ್: ವಿಮಾನಗಳು, ರೈಲುಗಳು, ಹೋಟೆಲ್‌ಗಳು ಮತ್ತು ಸ್ಥಳೀಯ ಕ್ಯಾಬ್‌ಗಳು.",
    "transit_feat_companion": "ಸಾರಿಗೆ ಒಡನಾಡಿ: ಆರೈಕೆದಾರರು ಪ್ರಯಾಣ, ಸಾಮಾನು ಮತ್ತು ಗಾಲಿಕುರ್ಚಿ ಬೆಂಬಲವನ್ನು ನಿರ್ವಹಿಸುತ್ತಾರೆ.",
    "transit_feat_dossier": "ವೈದ್ಯಕೀಯ ದಾಖಲೆ: ತಜ್ಞರಿಗೆ ಭೌತಿಕ ಮತ್ತು ಡಿಜಿಟಲ್ ವೈದ್ಯಕೀಯ ಫೈಲ್ ತಯಾರಿ.",
    "transit_feat_coordination": "ಗಮ್ಯಸ್ಥಾನ ಸಮನ್ವಯ: ಆರೈಕೆದಾರರು ಹಿರಿಯರೊಂದಿಗೆ ಇರುತ್ತಾರೆ, ಭೇಟಿಯ ಸಮಯದಲ್ಲಿ ಸಹಾಯ ಮಾಡುತ್ತಾರೆ, ಕುಟುಂಬವನ್ನು ನವೀಕರಿಸುತ್ತಾರೆ.",
    "transit_feat_medication": "ಔಷಧಿ ನಿರ್ವಹಣೆ: ಸಾರಿಗೆಯ ಸಮಯದಲ್ಲಿ ಸಕಾಲಿಕ ಜ್ಞಾಪನೆಗಳು ಮತ್ತು ಡೋಸೇಜ್ ಬೆಂಬಲ.",
    "transit_feat_crowd": "ಜನಸಂದಣಿ ಮತ್ತು ಚಲನಶೀಲತೆ: ಆದ್ಯತೆಯ ಸರತಿ ಸಾಲುಗಳು, ಜನಸಂದಣಿ ಮತ್ತು ದೇವಸ್ಥಾನದ ಆಸನಗಳೊಂದಿಗೆ ಸಹಾಯ.",
    "transit_feat_dietary": "ಆಹಾರದ ಅನುಸರಣೆ: ಪ್ರಯಾಣ/ಕಾರ್ಯಕ್ರಮಗಳ ಸಮಯದಲ್ಲಿ ಸೂಚಿಸಲಾದ ಆಹಾರಕ್ರಮದ ಕಟ್ಟುನಿಟ್ಟಾದ ನಿರ್ವಹಣೆ.",
    "transit_feat_itineraries": "ಆರಾಮದಾಯಕ ಪ್ರಯಾಣದ ವಿವರಗಳು: ಸಾಕಷ್ಟು ವಿಶ್ರಾಂತಿಯೊಂದಿಗೆ ಆರಾಮದಾಯಕ ಪ್ರಯಾಣದ ಯೋಜನೆ.",
    "transit_feat_dest_coordination": "ಗಮ್ಯಸ್ಥಾನ ಸಮನ್ವಯ: ಈವೆಂಟ್‌ಗಳ ಸಮಯದಲ್ಲಿ ಬೆಂಬಲ ಮತ್ತು ಸುರಕ್ಷಿತವಾಗಿ ಮನೆಗೆ ಮರಳುವುದು."
  },
  ta: {
    "care_super_title": "மன அமைதிக்கான மதிப்பு திட்டங்கள்",
    "care_subtitle_1": "உங்கள் ஆரோக்கியமே எங்கள் முன்னுரிமை.",
    "care_subtitle_2": "அடுத்த தலைமுறை பராமரிப்பு, மனித நேயம்.",
    "care_subtitle_3": "முதியோர் பராமரிப்பு, மன அமைதி.",
    "home_super_title": "சுயாதீன வாழ்க்கையை மேம்படுத்துங்கள்",
    "home_title": "ஹோம் எசென்ஷியல் பிளான்",
    "value_plans_subtitle": "மன அமைதிக்கான மதிப்பு திட்டங்கள்",
    "active_plan_banner": "செயலில் உள்ள திட்டம்",
    "current_plan": "✓ தற்போதைய திட்டம்",
    "already_subscribed": "ஏற்கனவே சந்தா சேர்ந்துள்ளார்",
    "subscribe_now": "இப்போது சந்தா சேரவும்",
    "per_cycle": "ஒரு {{suffix}}க்கு",
    "days_suffix": "{{days}} நாட்கள்",
    "home_disclaimer": "குறிப்பு: ஆயுக்சா சேவை கட்டணம் மட்டுமே தள்ளுபடி செய்யப்படுகிறது. விற்பனையாளர் கட்டணங்கள், உதிரி பாகங்கள் এবং பிற மூன்றாம் தரப்பு செலவுகள் வாடிக்கையாளரால் செலுத்தப்பட வேண்டும்.",
    "on_demand": "தேவையின் பேரில்",
    "transit_care_title": "ஆயுக்சா டிரான்சிட் கேர்",
    "transit_care_subtitle": "முழுமையாக பயிற்சி பெற்ற பராமரிப்பாளர்களுடன் மருத்துவ துணை, ஆன்மீக எஸ்கார்ட் அல்லது ஓய்வு நேர பயணங்களைப் பெறுங்கள்.",
    "pay_per_trip": "ஒரு பயணத்திற்கு கட்டணம் செலுத்துங்கள்",
    "request_now": "இப்போது கோருங்கள்",
    "why_ayuxa": "ஏன் ஆயுக்சா?",
    "my_memberships": "எனது சந்தாக்கள்",
    "manage_plans": "உங்கள் திட்டங்களை பார்க்க, புதுப்பிக்க மற்றும் நிர்வகிக்க",
    "plan_usage_policy": "திட்ட பயன்பாட்டுக் கொள்கை",
    "policy_content": "மாதாந்திர மற்றும் காலாண்டு நன்மைகள் பயன்படுத்தவும் அல்லது இழக்கவும் என்ற அடிப்படையில் செயல்படுகின்றன. பயன்படுத்தப்படாத வருகைகள் அடுத்த பில்லிங் சுழற்சிக்கு மாற்றப்படாது.",
    "terms_conditions_title": "விதிமுறைகள் & நிபந்தனைகள்",
    "medical_transit_title": "மருத்துவ போக்குவரத்து (மாநிலத்திற்கு வெளியே)",
    "spiritual_leisure_title": "ஆன்மீக மற்றும் ஓய்வு நேர பயணங்கள்",
    "transit_feat_booking": "முழுமையான முன்பதிவு: விமானங்கள், ரயில்கள், ஹோட்டல்கள் மற்றும் உள்ளூர் டாக்சிகள்.",
    "transit_feat_companion": "பயணத் துணை: பராமரிப்பாளர் பயணம், லக்கேஜ் மற்றும் சக்கர நாற்காலி ஆதரவைக் கையாளுகிறார்.",
    "transit_feat_dossier": "மருத்துவ ஆவணம்: நிபுணர்களுக்கான உடல் மற்றும் டிஜிட்டல் மருத்துவ கோப்பு தயாரிப்பு.",
    "transit_feat_coordination": "இலக்கு ஒருங்கிணைப்பு: பராமரிப்பாளர் முதியவருடன் தங்கி, வருகையின் போது உதவி செய்து, குடும்பத்தினருக்குத் தெரிவிக்கிறார்.",
    "transit_feat_medication": "மருந்து மேலாண்மை: பயணத்தின் போது சரியான நேரத்தில் நினைவூட்டல்கள் மற்றும் அளவு ஆதரவு.",
    "transit_feat_crowd": "கூட்டம் & நடமாட்டம்: முன்னுரிமை வரிசைகள், கூட்டங்கள் மற்றும் கோவில் இருக்கைகளில் உதவி.",
    "transit_feat_dietary": "உணவுக் கட்டுப்பாடு: பயணம்/நிகழ்வுகளின் போது பரிந்துரைக்கப்பட்ட உணவை கண்டிப்பாக பராமரித்தல்.",
    "transit_feat_itineraries": "வசதியான பயணத்திட்டம்: போதுமான ஓய்வுடன் வசதியைச் சுற்றி திட்டமிடப்பட்ட பயணம்.",
    "transit_feat_dest_coordination": "இலக்கு ஒருங்கிணைப்பு: நிகழ்வுகளின் போது ஆதரவு மற்றும் பாதுகாப்பான வீடு திரும்புதல்."
  },
  te: {
    "care_super_title": "మనశ్శాంతి కోసం విలువైన ప్లాన్లు",
    "care_subtitle_1": "మీ ఆరోగ్యమే మా ప్రాధాన్యత.",
    "care_subtitle_2": "నెక్స్ట్-జెన్ కేర్, హ్యూమన్ టచ్.",
    "care_subtitle_3": "వృద్ధుల సంరక్షణ, మనశ్శాంతి.",
    "home_super_title": "స్వతంత్ర జీవనానికి సాధికారత",
    "home_title": "హోమ్ ఎసెన్షియల్ ప్లాన్",
    "value_plans_subtitle": "మనశ్శాంతి కోసం విలువైన ప్లాన్లు",
    "active_plan_banner": "యాక్టివ్ ప్లాన్",
    "current_plan": "✓ ప్రస్తుత ప్లాన్",
    "already_subscribed": "ఇప్పటికే సబ్‌స్క్రైబ్ చేసారు",
    "subscribe_now": "ఇప్పుడే సబ్‌స్క్రైబ్ చేయండి",
    "per_cycle": "ప్రতি {{suffix}}కి",
    "days_suffix": "{{days}} రోజులు",
    "home_disclaimer": "గమనిక: ఆయుక్సా సేవా రుసుములు మాత్రమే మినహాయించబడతాయి. విక్రేత ఛార్జీలు, విడి భాగాలు మరియు ఇతర మూడవ పక్ష ఖర్చులు క్లయింట్ చెల్లించాల్సి ఉంటుంది.",
    "on_demand": "డిమాండ్ మేరకు",
    "transit_care_title": "ఆయుక్సా ట్రాన్సిట్ కేర్",
    "transit_care_subtitle": "శిక్షణ పొందిన కేర్‌గివర్‌లతో వైద్యపరమైన తోడు, ఆధ్యాత్మిక ఎస్కార్ట్ లేదా వినోద ప్రయాణాలను పొందండి.",
    "pay_per_trip": "ప్రతి ట్రిప్‌కు చెల్లించండి",
    "request_now": "ఇప్పుడే అభ్యర్థించండి",
    "why_ayuxa": "ఎందుకు ఆయుక్సా?",
    "my_memberships": "నా సభ్యత్వాలు",
    "manage_plans": "మీ ప్లాన్‌లను వీక్షించండి, పునరుద్ధరించండి మరియు నిర్వహించండి",
    "plan_usage_policy": "ప్లాన్ వినియోగ విధానం",
    "policy_content": "నెలవారీ మరియు త్రైమాసిక ప్రయోజనాలు ఉపయోగించుకోండి లేదా కోల్పోండి అనే ప్రాతిపదికన పని చేస్తాయి. ఉపయోగించని సందర్శనలు తదుపరి బిల్లింగ్ చక్రానికి బదిలీ చేయబడవు.",
    "terms_conditions_title": "నిబంధనలు & షరతులు",
    "medical_transit_title": "వైద్య రవాణా (రాష్ట్రం వెలుపల)",
    "spiritual_leisure_title": "ఆధ్యాత్మిక మరియు వినోద ప్రయాణాలు",
    "transit_feat_booking": "ఎండ్-టు-ఎండ్ బుకింగ్: విమానాలు, రైళ్లు, హోటళ్లు మరియు స్థానిక క్యాబ్‌లు.",
    "transit_feat_companion": "రవాణా తోడు: కేర్‌గివర్ ప్రయాణం, సామాను మరియు వీల్‌చైర్ సహాయాన్ని చూసుకుంటారు.",
    "transit_feat_dossier": "వైద్య పత్రాల తయారీ: నిపుణుల కోసం ఫిజికల్ మరియు డిజిటల్ మెడికల్ ఫైల్ ప్రిపరేషన్.",
    "transit_feat_coordination": "గమ్యస్థాన సమన్వయం: కేర్‌గివర్ వృద్ధులతోనే ఉంటారు, సందర్శనలో సహాయం చేస్తారు, కుటుంబానికి సమాచారం ఇస్తారు.",
    "transit_feat_medication": "మందుల నిర్వహణ: ప్రయాణంలో సకాలంలో రిమైండర్‌లు మరియు మోతాదు సహాయం.",
    "transit_feat_crowd": "సమూహం & చలనశీలత: ప్రాధాన్యత క్యూలు, రద్దీ మరియు దేవాలయ ఆసనాలలో సహాయం.",
    "transit_feat_dietary": "ఆహార నియమాలను పాటించడం: ప్రయాణాలు/ఈవెంట్‌ల సమయంలో సూచించిన ఆహారాన్ని ఖచ్చితంగా పాటించడం.",
    "transit_feat_itineraries": "సౌకర్యవంతమైన ప్రయాణ ప్రణాళిక: తగినంత విశ్రాంతితో కూడిన సౌకర్యవంతమైన ప్రయాణ ప్రణాళిక.",
    "transit_feat_dest_coordination": "గమ్యస్థాన సమన్వయం: ఈవెంట్‌ల సమయంలో సహాయం మరియు సురక్షితంగా ఇంటికి తిరిగి రావడం."
  },
  ml: {
    "care_super_title": "മനസമാധാനത്തിനായുള്ള മൂല്യ പദ്ധതികൾ",
    "care_subtitle_1": "നിങ്ങളുടെ ആരോഗ്യമാണ് ഞങ്ങളുടെ മുൻഗണന.",
    "care_subtitle_2": "അടുത്ത തലമുറ പരിചരണം, മാനുഷിക സ്പർശം.",
    "care_subtitle_3": "മുതിർന്നവരുടെ പരിചരണം, സമാധാനം.",
    "home_super_title": "സ്വതന്ത്ര ജീവിതം ശാക്തീകരിക്കുക",
    "home_title": "ഹോം എസൻഷ്യൽ പ്ലാൻ",
    "value_plans_subtitle": "മനസമാധാനത്തിനായുള്ള മൂല്യ പദ്ധതികൾ",
    "active_plan_banner": "സജീവ പ്ലാൻ",
    "current_plan": "✓ നിലവിലെ പ്ലാൻ",
    "already_subscribed": "നിലവിൽ സബ്‌സ്‌ക്രൈബ് ചെയ്‌തിട്ടുണ്ട്",
    "subscribe_now": "ഇപ്പോൾ സബ്‌സ്‌ക്രൈബ് ചെയ്യുക",
    "per_cycle": "ഓരോ {{suffix}}നും",
    "days_suffix": "{{days}} ദിവസങ്ങൾ",
    "home_disclaimer": "ശ്രദ്ധിക്കുക: ആയുക്സ സർവീസ് ചാർജുകൾ മാത്രമേ ഒഴിവാക്കൂ. വെണ്ടർ ചാർജുകൾ, спаре പാർട്സുകൾ, മറ്റ് മൂന്നാം കക്ഷി ചെലവുകൾ എന്നിവ ക്ലയന്റ് നൽകേണ്ടതാണ്.",
    "on_demand": "ആവശ്യാനുസരണം",
    "transit_care_title": "ആയുക്സ ട്രാൻസിറ്റ് കെയർ",
    "transit_care_subtitle": "പരിശീലനം സിദ്ധിച്ച പരിചാരകർക്കൊപ്പം മെഡിക്കൽ സഹായം, ആത്മീയ അകമ്പടി അല്ലെങ്കിൽ വിനോദ യാത്രകൾ നേടുക.",
    "pay_per_trip": "ഓരോ യാത്രയ്ക്കും പണം നൽകുക",
    "request_now": "ഇപ്പോൾ അഭ്യർത്ഥിക്കുക",
    "why_ayuxa": "എന്തുകൊണ്ട് ആയുക്സ?",
    "my_memberships": "എന്റെ അംഗത്വങ്ങൾ",
    "manage_plans": "നിങ്ങളുടെ പ്ലാനുകൾ കാണുക, പുതുക്കുക, നിയന്ത്രിക്കുക",
    "plan_usage_policy": "പ്ലാൻ ഉപയോഗ നയം",
    "policy_content": "പ്രതിമാസ, ത്രൈമാസ ആനുകൂല്യങ്ങൾ ഉപയോഗിക്കുക അല്ലെങ്കിൽ നഷ്ടപ്പെടുത്തുക എന്ന അടിസ്ഥാനത്തിലാണ് പ്രവർത്തിക്കുന്നത്. ഉപയോഗിക്കാത്ത സന്ദർശനങ്ങൾ അടുത്ത ബില്ലിംഗ് ചക്രത്തിലേക്ക് മാറ്റില്ല.",
    "terms_conditions_title": "വ്യവസ്ഥകളും നിബന്ധനകളും",
    "medical_transit_title": "മെഡിക്കൽ ട്രാൻസിറ്റ് (സംസ്ഥാനത്തിന് പുറത്ത്)",
    "spiritual_leisure_title": "ആത്മീയവും വിനോദപരവുമായ യാത്രകൾ",
    "transit_feat_booking": "എൻഡ്-ടു-എൻഡ് ബുക്കിംഗ്: ഫ്ലൈറ്റുകൾ, ട്രെയിനുകൾ, ഹോട്ടലുകൾ, പ്രാദേശിക ക്യാബുകൾ.",
    "transit_feat_companion": "ട്രാൻസിറ്റ് കമ്പാനിയൻ: പരിചാരകൻ യാത്ര, ലഗേജ്, വീൽചെയർ പിന്തുണ എന്നിവ കൈകാര്യം ചെയ്യുന്നു.",
    "transit_feat_dossier": "മെഡിക്കൽ ഫയൽ തയ്യാറാക്കൽ: വിദഗ്ദ്ധർക്കായി ഭൗതികവും ഡിജിറ്റലുമായ മെഡിക്കൽ ഫയലുകൾ തയ്യാറാക്കൽ.",
    "transit_feat_coordination": "ലക്ഷ്യസ്ഥാന കോർഡിനേഷൻ: പരിചാരകൻ മുതിർന്നവർക്കൊപ്പം താമസിക്കുന്നു, സന്ദർശന വേളയിൽ സഹായിക്കുന്നു, കുടുംബത്തിന് അപ്ഡേറ്റുകൾ നൽകുന്നു.",
    "transit_feat_medication": "മരുന്ന് മാനേജ്മെന്റ്: യാത്രയ്ക്കിടയിൽ കൃത്യസമയത്തുള്ള ഓർമ്മപ്പെടുത്തലുകളും ഡോസേജ് പിന്തുണയും.",
    "transit_feat_crowd": "ജനക്കൂട്ടവും ചലനാത്മകതയും: മുൻഗണനാ ക്യൂകൾ, ജനക്കൂട്ടം, ക്ഷേത്ര ഇരിപ്പിടങ്ങൾ എന്നിവയിൽ സഹായം.",
    "transit_feat_dietary": "ഭക്ഷണക്രമം പാലിക്കൽ: യാത്രകളിലും പരിപാടികളിലും നിർദ്ദേശിച്ച ഭക്ഷണക്രമം കർശനമായി പാലിക്കൽ.",
    "transit_feat_itineraries": "ആശ്വാസകരമായ യാത്രാ പദ്ധതി: ആവശ്യത്തിന് വിശ്രമത്തോടെയുള്ള സുഖകരമായ യാത്രാ പദ്ധതി.",
    "transit_feat_dest_coordination": "ലക്ഷ്യസ്ഥാന കോർഡിനേഷൻ: പരിപാടികളിൽ പിന്തുണയും സുരക്ഷിതമായി മടങ്ങിയെത്തലും."
  },
  mr: {
    "care_super_title": "मनःशांतीसाठी मूल्य योजना",
    "care_subtitle_1": "तुमचे आरोग्य आमचे प्राधान्य आहे.",
    "care_subtitle_2": "पुढील पिढीची काळजी, मानवी स्पर्श.",
    "care_subtitle_3": "ज्येष्ठांची काळजी, मनःशांती.",
    "home_super_title": "स्वतंत्र जीवनाचे सक्षमीकरण",
    "home_title": "होम एसेन्शियल प्लॅन",
    "value_plans_subtitle": "मनःशांतीसाठी मूल्य योजना",
    "active_plan_banner": "सक्रिय प्लॅन",
    "current_plan": "✓ चालू प्लॅन",
    "already_subscribed": "आधीच सबस्क्राइब केले आहे",
    "subscribe_now": "आता सबस्क्राइब करा",
    "per_cycle": "प्रति {{suffix}}",
    "days_suffix": "{{days}} दिवस",
    "home_disclaimer": "टीप: फक्त आयुक्सा सेवा शुल्क माफ केले जाते. विक्रेता शुल्क, सुटे भाग आणि इतर तृतीय-पक्ष खर्च ग्राहकाला द्यावे लागतील.",
    "on_demand": "मागणीनुसार",
    "transit_care_title": "आयुक्सा ट्रान्झिट केअर",
    "transit_care_subtitle": "पूर्णपणे प्रशिक्षित केअरगिव्हरसह वैद्यकीय सोबत, आध्यात्मिक एस्कॉर्ट किंवा सहली मिळवा.",
    "pay_per_trip": "प्रति ट्रिप पैसे द्या",
    "request_now": "आता विनंती करा",
    "why_ayuxa": "आयुक्सा का?",
    "my_memberships": "माझ्या सदस्यत्वे",
    "manage_plans": "तुमचे प्लॅन्स पहा, नूतनीकरण करा आणि व्यवस्थापित करा",
    "plan_usage_policy": "प्लॅन वापर पॉलिसी",
    "policy_content": "मासिक आणि त्रैमासिक फायदे वापरा किंवा गमावा या तत्त्वावर काम करतात. न वापरलेले दौरे पुढील बिलिंग चक्रात वर्ग केले जाणार नाहीत.",
    "terms_conditions_title": "नियम व अटी",
    "medical_transit_title": "वैद्यकीय वाहतूक (राज्याबाहेर)",
    "spiritual_leisure_title": "आध्यात्मिक आणि सहली",
    "transit_feat_booking": "एंड-टू-एंड बुकिंग: विमाने, ट्रेन, हॉटेल आणि स्थानिक कॅब.",
    "transit_feat_companion": "प्रवास सोबती: केअरगिव्हर प्रवास, सामान आणि व्हीलचेअर सहाय्य सांभाळतो.",
    "transit_feat_dossier": "वैद्यकीय दस्तऐवजीकरण: तज्ञांसाठी भौतिक आणि डिजिटल वैद्यकीय फाइलची तयारी.",
    "transit_feat_coordination": "गंतव्य समन्वय: केअरगिव्हर ज्येष्ठांसोबत राहतो, भेटीदरम्यान मदत करतो, कुटुंबाला अपडेट करतो.",
    "transit_feat_medication": "औषध व्यवस्थापन: प्रवासादरम्यान वेळेवर स्मरणपत्रे आणि डोस समर्थन.",
    "transit_feat_crowd": "गर्दी आणि हालचाल: प्राधान्य रांगा, गर्दी आणि मंदिरातील आसनांमध्ये मदत.",
    "transit_feat_dietary": "आहार पालन: प्रवास/कार्यक्रमांदरम्यान विहित आहाराचे काटेकोर पालन.",
    "transit_feat_itineraries": "आरामदायी प्रवास कार्यक्रम: पुरेशा विश्रांतीसह नियोजित प्रवास.",
    "transit_feat_dest_coordination": "गंतव्य समन्वय: कार्यक्रमांदरम्यान समर्थन आणि सुरक्षित घर वापसी."
  },
  bn: {
    "care_super_title": "মনের শান্তির জন্য ভ্যালু প্ল্যান",
    "care_subtitle_1": "আপনার স্বাস্থ্য আমাদের অগ্রাধিকার।",
    "care_subtitle_2": "পরবর্তী প্রজন্মের যত্ন, মানবিক স্পর্শ।",
    "care_subtitle_3": "প্রবীণদের যত্ন, মানসিক শান্তি।",
    "home_super_title": "স্বাধীন জীবনযাপনকে শক্তিশালী করুন",
    "home_title": "হোম এসেনশিয়াল প্ল্যান",
    "value_plans_subtitle": "মনের শান্তির জন্য ভ্যালু প্ল্যান",
    "active_plan_banner": "সক্রিয় প্ল্যান",
    "current_plan": "✓ বর্তমান প্ল্যান",
    "already_subscribed": "ইতিমধ্যে সাবস্ক্রাইব করা আছে",
    "subscribe_now": "এখনই সাবস্ক্রাইব করুন",
    "per_cycle": "প্রতি {{suffix}}",
    "days_suffix": "{{days}} দিন",
    "home_disclaimer": "দ্রষ্টব্য: কেবল আয়ুক্সা পরিষেবা ফি মওকুফ করা হয়। বিক্রেতা চার্জ, খুচরা যন্ত্রাংশ এবং অন্যান্য তৃতীয় পক্ষের খরচ গ্রাহককে পরিশোধ করতে হবে।",
    "on_demand": "অন-ডিমান্ড",
    "transit_care_title": "আয়ুক্সা ট্রানজিট কেয়ার",
    "transit_care_subtitle": "সম্পূর্ণ প্রশিক্ষিত কেয়ারগিভারের সাথে চিকিৎসা সহায়তা, আধ্যাত্মিক এসকর্ট বা অবসর ভ্রমণ লাভ করুন।",
    "pay_per_trip": "প্রতি ট্রিপে পেমেন্ট",
    "request_now": "এখনই অনুরোধ করুন",
    "why_ayuxa": "কেন আয়ুক্সা?",
    "my_memberships": "আমার মেম্বারশিপ",
    "manage_plans": "আপনার প্ল্যান দেখুন, রিনিউ করুন এবং পরিচালনা করুন",
    "plan_usage_policy": "প্ল্যান ব্যবহার নীতি",
    "policy_content": "মাসিক এবং ত্রৈমাসিক সুবিধাগুলি ব্যবহার না করলে বাতিল হয়ে যাবে। অব্যবহৃত ভিজিট পরবর্তী বিলিং চক্রে স্থানান্তরিত হবে না।",
    "terms_conditions_title": "শর্তাবলী",
    "medical_transit_title": "মেডিকেল ট্রানজিট (রাজ্যের বাইরে)",
    "spiritual_leisure_title": "আধ্যাত্মিক ও অবসর ভ্রমণ",
    "transit_feat_booking": "শুরু থেকে শেষ পর্যন্ত বুকিং: বিমান, ট্রেন, হোটেল এবং লোকাল ক্যাব।",
    "transit_feat_companion": "ভ্রমণ সঙ্গী: কেয়ারগিভার ভ্রমণ, লগেজ এবং হুইলচেয়ার সহায়তা প্রদান করেন।",
    "transit_feat_dossier": "মেডিকেল ডসিয়ার: বিশেষজ্ঞদের জন্য শারীরিক এবং ডিজিটাল মেডিকেল ফাইল প্রস্তুত করা।",
    "transit_feat_coordination": "গন্তব্য সমন্বয়: কেয়ারগিভার প্রবীণ ব্যক্তির সাথে থাকেন, ভিজিটে সহায়তা করেন, পরিবারকে আপডেট দেন।",
    "transit_feat_medication": "ওষুধের ব্যবস্থাপনা: ভ্রমণের সময় সময়মতো রিমাইন্ডার এবং ডোজ সহায়তা।",
    "transit_feat_crowd": "ভিড় এবং গতিশীলতা: অগ্রাধিকার সারি, ভিড় এবং মন্দিরের আসনে সহায়তা।",
    "transit_feat_dietary": "খাদ্যাভ্যাস মেনে চলা: ভ্রমণ/অনুষ্ঠানের সময় নির্ধারিত পথ্য কঠোরভাবে বজায় রাখা।",
    "transit_feat_itineraries": "স্বাচ্ছন্দ্যময় ভ্রমণসূচী: পর্যাপ্ত বিশ্রামের সাথে স্বাচ্ছন্দ্যকে কেন্দ্র করে পরিকল্পিত ভ্রমণ।",
    "transit_feat_dest_coordination": "গন্তব্য সমন্বয়: অনুষ্ঠানের সময় সহায়তা এবং নিরাপদে ঘরে প্রত্যাবর্তন।"
  }
};

for (const lang of languages) {
  const filePath = path.join(localesDir, `${lang}.json`);
  if (!fs.existsSync(filePath)) {
    console.log(`Skipping missing file: ${filePath}`);
    continue;
  }
  
  try {
    const fileContent = fs.readFileSync(filePath, 'utf8');
    const data = JSON.parse(fileContent);
    
    if (!data.plans) {
      data.plans = {};
    }
    
    // Merge new keys into plans namespace
    data.plans = {
      ...data.plans,
      ...newKeys[lang]
    };
    
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
    console.log(`Successfully updated translations for "${lang}"`);
  } catch (err) {
    console.error(`Error processing language "${lang}":`, err);
  }
}
console.log('Done!');
